### GET request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Shashank",
  "email": "shasha123@gmail.com",
  "address": "Palatino bend",
  "dateOfBirth": "2000-09-01",
  "registrationDate": "2023-03-09"
}

###